name: Deploy Odyssea Lymphea to WordPress

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./odyssea
      run: npm install

    - name: Build theme
      working-directory: ./odyssea
      run: bash build-theme.sh

    - name: Verify build
      working-directory: ./odyssea
      run: |
        echo "Checking if assets were built..."
        ls -la assets/
        ls -la asset-manifest.php
        echo "Build verification complete!"

    - name: Deploy to WordPress via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./odyssea/
        server-dir: /wp-content/themes/odyssea/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/package-lock.json

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "Theme deployed to /wp-content/themes/odyssea/"
        echo "Remember to activate the theme in WordPress Admin if not already active."

    - name: Deployment failed notification
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Check the logs above for error details."
